#!/usr/bin/env python3
import os
import random


def random_img_path_call(path):
    imgs = os.listdir(path)
    return os.path.join(path,random.choice(imgs))

def change_bg(path):
    cmd = 'feh --bg-fill ' + path
    print(cmd)
    os.system(cmd)

def main():
    base_path = '/home/lius/pictures/bg-wall/'
    random_img_path = random_img_path_call(base_path)
    change_bg(random_img_path)

if __name__ == "__main__":
    main()


