#!/usr/bin/env bash

changeVolume(){
    v1=$(amixer -D pulse sget Master)
    volume=`echo ${v1:0-10:10} | grep -oP '\[\d*\%\]' | xargs echo | sed 's/[^0-9]//g'`

    dunstify -a "changevolume" -u low -r "9993" -h int:value:"$volume" -i "volume-$1" "Volume: ${volume}%" -t 2000
}

(amixer -D pulse sset Master 5%+ && pkill -RTMIN+1 i3blocks) >> /dev/null

changeVolume

